### ISSUE TITLE
Интеграция не находится в списке доступных

### ISSUE THREAD

**Issue by MaximSN** [alryaz/hass-lkcomu-interrao#1]
Добрый день.
Установил новую интеграцию через hacs, но не могу ее добавить в HA.
Находится только мосэнергосбыт.
Эти интеграции можно одновременно устанавливать? Они не конфликтуют?
Старую не хочется сразу удалять, там работает автоматизация по отправке показаний счетчиков.
<img width="522" alt="new_energosbyt" src="https://user-images.githubusercontent.com/57829001/122195093-b57db080-ce9e-11eb-8ca4-88436e4be6cc.PNG">
<img width="395" alt="energosbyt_integration" src="https://user-images.githubusercontent.com/57829001/122195120-badafb00-ce9e-11eb-8083-7c8bd07f231c.PNG">

**Comment by Aliens1973** [comment]
у меня так же, добавил в конфиг: 
lkcomu_interrao:
  username: !secret mosenergosbyt_username
  password: !secret mosenergosbyt_password
и она сама появилась

**Comment by MaximSN** [comment]
если через конфиг добавить, то все равно не появляется.
а в логах ошибки
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.lkcomu_interrao._base
Source: custom_components/lkcomu_interrao/_base.py:220
Integration: Личный кабинет Интер РАО (Энергосбыт) (documentation, issues)
First occurred: 14:15:24 (2 occurrences)
Last logged: 14:20:24

Error occurred: TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'")

**Comment by Aliens1973** [comment]
из меню hacs установил ее по ссылке на репозиторий: https://github.com/alryaz/hass-lkcomu-interrao, ребутнул ХА. В настройки-интеграции не увидел ее, добавил в конфиг то что писал выше, опять ребутнул ХА и интеграция появилась в: настройки- интеграции.
И да, одновременно с мосэнерго работает

**Comment by alryaz** [comment]
Pull-request-ы в hacs/default проходят долго. Ожидайте.

**Comment by alryaz** [comment]
Пока что продвижения по данному вопросу нет (последние добавления в `hacs/default` - 27 Июня).

Если у кого-то есть разрешение на оставление review, то: [https://github.com/hacs/default/pull/995](https://github.com/hacs/default/pull/995)

**Comment by alryaz** [comment]
Свершилось добавление в hacs/default, закрываю issue.
