### ISSUE TITLE
feature request: отдельные устройства для лицевых счетов

### ISSUE THREAD

**Issue by IATkachenko** [alryaz/hass-lkcomu-interrao#13]
# Как работает сейчас
У интеграции есть только список объектов. Если к аккаунту привязано несколько ЛС, то все сенсоры на странице интеграции в перемешку. 
# Как хочется
Отдельное устройство на каждый лицевой счет.
## dev hint
То, к какому устройству принадлежит сенсор (Entity, в общем случае) в HA определяется полем identifiers в свойстве `device_info`
```python
        { "identifiers": {(DOMAIN, self.unique_id)} }
        
```
все Entity с одинаковыми `identifiers` будут отнесены к одному устройству

**Comment by alryaz** [comment]
Согласен, что такая группировка имела бы смысл, но изначально не закладывал её из-за определения "устройств" в документации HA.

По факту единственным устройством в рамках данного компонента выступал бы счётчик ЖКУ (с сопутствующими сенсорами, которые относятся, например, к функционированию АСКУЭ). Но, к сожалению, дополнительные данные не подаются, поэтому пока что сенсор счётчика атомарный.

Тем не менее, согласен, что некая группировка подействовала бы компоненту на пользу. Рассмотрю добавление данного функционала в будущем обновлении.

**Comment by alryaz** [comment]
Функционал добавлен, присутствует в релизе v0.0.22.

До этого обкатывал его на других компонентах; действительно, если учётных записей под 20 штук (что происходит у меня при тестировании), на этот балаган проще смотреть.

Только вот, не знаю, поступил ли я правильно, но решил ещё добавить `suggested_area` в примесь ко всем остальным данным о виртуальном устройстве. Группирование теперь выглядит ещё веселее, только вот это может инвазивно сказать на пуристских конфигурациях, где комнаты очень тщательно переименовываются. С другой стороны, это редактируется довольно просто.

**Comment by IATkachenko** [comment]
Группировка работает хорошо. Спасибо, стало гораздо удобнее.

"Пространство" (на мой взгляд) -- весьма спорное решение. У меня, например, к списку комнат в доме добавились все адреса привязанные к лицевым счетам и стало не очень удобно. Если пространство для устройства нужно, то его можно всегда задать в ручную. А вот удалить не получается: интеграция пересоздает пространства при перезапуске. Пришлось создавать отдельное пространство. Раньше обходился тем что просто не указывал помещение если устройство не локализовано в комнате дома.

**Comment by alryaz** [comment]
Отключил в main передачу данных о комнате. В последующем обновлении добавлю какую-нибудь галочку для этого.

**Comment by NikitaKorneev** [comment]
Шикарное изменение! Большое спасибо!
