### ISSUE TITLE
Сломалась авторизация, Требует капчу

### ISSUE THREAD

**Issue by bigsem89** [alryaz/hass-lkcomu-interrao#15]
Logger: custom_components.lkcomu_interrao
Source: custom_components/lkcomu_interrao/__init__.py:277
Integration: Личный кабинет Интер РАО (Энергосбыт) (documentation, issues)
First occurred: 22:54:33 (3 occurrences)
Last logged: 22:55:01

[moscow/9***2] Невозможно выполнить авторизацию: EnergosbytException('Authentication failed', 114, 'Не подтверждена капча')

**Comment by alryaz** [comment]
Здравствуйте! Пожалуйста, свяжитесь со мной в Telegram: @alryaz.

**Comment by alryaz** [comment]
Ошибка, как оказалось, действительно решается вводом капчи. В v0.1.0 добавил немного иное уведомление об ошибке авторизации; к v0.2.0 добавлю какое-нибудь более ясное уведомление.
