### ISSUE TITLE
Добавить текущий тариф

### ISSUE THREAD

**Issue by NikitaKorneev** [alryaz/hass-lkcomu-interrao#2]
В архивной версии можно было найти текущий тарий. Сейчас ни в одной сущьности этого нет.

Можно ли это исправить?

**Comment by alryaz** [comment]
Данные о тарифах (описание тарифа, стоимость за единицу, название) добавлены в лицевые счета (только аккаунты _Быт_-типа) последним коммитом. Если речь идёт об этих сведениях, то в таком случае обновите интеграцию.

Обновлённый лицевой счёт (на примере Мосэнергосбыт):
![Снимок экрана лицевого счёта](https://raw.githubusercontent.com/alryaz/hass-lkcomu-interrao/a1160506202c998ac6f7a72ecb5139e04644a7b7/images/providers/mes/accounts.png)

Делать попытку разбора периодов применения тарифных зон, к сожалению, опасно и неустойчиво, так как формат данных, приходящий от сервера, вольный. Ввиду этого

**Comment by NikitaKorneev** [comment]
@alryaz Я говорил именно о стоимости кВ*ч. Обновил - вижу! Спасибо!
