### ISSUE TITLE
МОСОБЛЕИРЦ

### ISSUE THREAD

**Issue by Psytoshgen** [alryaz/hass-lkcomu-interrao#24]
Можно ли подключить систему МОСОБЛЕИРЦ? в частности не ясно как Долгопрудный вообще добавить.

**Comment by alryaz** [comment]
МосОблЕИРЦ можно попробовать добавить в ЛК Мосэнергосбыт.
Данный компонент поддерживает API только нескольких провайдеров, которые используют ЛК, аналогичный https://my.mosenergosbyt.ru.
