### ISSUE TITLE
Вредоносная активность

### ISSUE THREAD

**Issue by booroondookZ** [alryaz/hass-lkcomu-interrao#25]
Интеграция отключилась. Причина - в моем личном кабинете Мосэнергосбыта сообщение: 
_Уважаемый пользователь!
C Вашего IP-адреса (ХХХ.ХХХ.ХХХ.ХХХ) была зафиксирована вредоносная активность при обращении к Единому Личному кабинету АО Мосэнергосбыт и ООО МосОблЕИРЦ.
В связи с этим доступ с Вашего IP-адреса был временно заблокирован.
Обращаем внимание: Ваш IP-адрес будет автоматически разблокирован в течение 3 часов._
Подозреваю, что это "бан" возник из-за слишком частых обращений интеграции к личному кабинету.
Может быть, есть какой-то способ снизить периодичность обращения к личному кабинету? Например, до двух-трех раз в сутки.
P.S. И вот, что ещё. На сайте Мосэнергосбыта написано, что теперь "Личный кабинет" будет доступен не круглосуточно, а только с 06:00 до 00:00 по московскому времени (а на сайте МосОблЕИРца - с 07:00 до 23:00). В остальное время суток сайты "my.mosenergosbyt.ru" и "lkk.mosobleirc.ru" даже не пингуются. И это тоже вызывает ошибку в интеграции.

**Comment by frfstu** [comment]
Тоже самое со вчерашнего вечера! Техническая поддержка при обращении по телефону +74995509550 ссылается на блокировку личных кабинетов клиентов для обеспечения их безопасности, в связи с невыясненого характера массовой вредоносной активностью! На мой запрос информации о причастности моего ip адреса(на который ссылается в своём уведомлении интеграция) к вредоносной активности, для дальнейшей её передачи в правоохранительные органы, оператор техподдержки Ксения предоставлять отказалась, ссылаясь на отсутствие информации и на то, что предоставление информации письменно, производится ТОЛЬКО при письменном обращении (что является нарушением ГК РФ, ФЗ об информации, информационных технологиях и о защите информации, и является уголовно наказуемым деянием в соответствии с УК РФ(отказ в предоставлении информации гражданину) ). Также по информации технической поддержки Мосэнергосбыт не имеет никакого отношения к разроботке и обслуживанию данной интеграции! Требую предоставления полной информации по данному факту вредоносной активности и конкретных данных на чём основано подозрение, от разработчика данной интеграции Александра Рязанцева!

**Comment by frfstu** [comment]
Отдельно уведомляю что при моём обращении к своему интернет провайдеру с вопросом о наличии со стороны моего ip адреса какой-либо аномальной либо вредоносной активности, мне был предоставлен утвердительный ответ об отсутствии таковой!!!

**Comment by frfstu** [comment]
Вот он итог использования сертификатов от центров сертификации достоверности узлов предоставляемых Американскими и Британскими компаниями! Имеет признаки подрыва информационной безопасности РФ, и подведомственно ФСБ и службе контрразведки.

**Comment by bigsem89** [comment]
Такая же фигня....забанили по IP на 3 часа.

**Comment by sasha8761** [comment]
Интеграция здесь не причем. При попытке зайти через официальное мобильное приложение "Мосэнергосбыт", оно выдает аналогичное предупреждение. Удалось зайти через VPN и передать показания.

**Comment by booroondookZ** [comment]
> Интеграция здесь не причем. При попытке зайти через официальное мобильное приложение "Мосэнергосбыт", оно выдает аналогичное предупреждение. Удалось зайти через VPN и передать показания.

Мне тоже удалось зайти с другого IP-адреса. Но... только один раз. На второй раз уже и этот новый адрес оказался забаненным.

**Comment by alexanderznamensky** [comment]
+1

**Comment by avbor** [comment]
` Нужно снизить частоту запросов со стороны интеграции.`
+1
Хорошо бы добавить подобную настройку в конфиг интеграции.

**Comment by frfstu** [comment]
У меня эта блокировка "на 3 часа" длится с с даты публикации этой темы!
Через браузер компьютера уже заходит(после моего звонка в мосэнергосбыт),
вчера проверял, а через интеграцию ни в какую!!! Так что причина в
интеграции, особенно учитывая что мосэнергосбыт никакого отношения к ее
разработке не имеет!

вс, 15 мая 2022 г., 15:28 Semyon Aronov ***@***.***>:

**Comment by alryaz** [comment]
Релиз v0.2.1 временно отключает компонент.
Отпишусь, как разберусь с авторизацией.

**Comment by alryaz** [comment]
**v2022.05.02** закрывает проблему с авторизацией (временно). Прошу протестировать.

**Comment by aatemes** [comment]
> **v2022.05.02** закрывает проблему с авторизацией (временно). Прошу протестировать.

Спасибо, проблема решена (провайдер МГТС, если это важно).

**Comment by alexanderznamensky** [comment]
+1 у меня заработало на двух разных серверах, с разными аккаунтами!

Александр, спасибо за вашу работу!

**Comment by booroondookZ** [comment]
Сегодня ночью узнал о вышедшем обновлении. Установил его. Перезапустил HA, но интеграция не заработала - сказался тот факт, что я "попал" в ночное время, когда сайт Личного кабинета Мосэнергосбыта был недоступен. Утром же я обнаружил, что интеграция так и не заработала, и мне снова пришлось перезапустить HA - только тогда интеграция, наконец-то, включилась.
В связи с этим вопрос - не выйдет ли так, что интеграция будет отключаться с приходом каждой ночи (т.е., отключением сайта Мосэнергосбыта), а для ее запуска нужно будет каждое утро вручную перезапускать HA?

**Comment by pervolianinen** [comment]
> В связи с этим вопросом - не ли так, что интеграция будет отключаться с приходом каждой ночи (т.е., отключением сайта Мосэнергосбыта), а для ее запуска необходимо будет каждое утро регулярно перезапускать HA?
Нет. Все нормально будет работать. НО только после того, как вы сможете первый раз нормально авторизоваться.

**Comment by booroondookZ** [comment]
Solved
