### ISSUE TITLE
Поставщик: ТНС Энерго

### ISSUE THREAD

**Issue by Aliens1973** [alryaz/hass-lkcomu-interrao#4]
Добрый день, можете добавить: ТНС Энерго Ярославль?

**Comment by alryaz** [comment]
Данный компонент поддерживает только ЛК _Интер РАО_, разработанные _Интегратор ИТ_ (применяющие единый формат личных кабинетов).
ТНС Энерго использует другой формат, что потребует написание иного адаптера и интеграции.

**Comment by Aliens1973** [comment]
жаль

**Comment by alryaz** [comment]
@Aliens1973 пожалуйста, напишите мне по электронной почте ([alryaz@xavux.com](mailto:alryaz@xavux.com))

**Comment by alryaz** [comment]
https://github.com/alryaz/hass-tns-energo
