### ISSUE TITLE
STATE_LOCKED

### ISSUE THREAD

**Issue by wadim-tim** [alryaz/hass-lkcomu-interrao#43]
Регистратор: homeassistant.const
Источник: helpers/deprecation.py:222
Первое сообщение: 10:39:55 (1 сообщений)
Последнее сообщение: 10:39:55

STATE_LOCKED was used from lkcomu_interrao, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.LOCKED instead, please report it to the author of the 'lkcomu_interrao' custom integration

**Comment by wadim-tim** [comment]
@alex-v-fraser

**Comment by alex-v-fraser** [comment]
[fixed](https://github.com/alryaz/hass-lkcomu-interrao/pull/38)
