### ISSUE TITLE
Ошибка get_payments/get_invoices

### ISSUE THREAD

**Issue by MaximSN** [alryaz/hass-lkcomu-interrao#5]
Если долго не закрывать интерфейс HA, то через некоторое время  сервер мосэнергосбыта закрывает сессию а интеграция об этом не знает
[home-assistant.log](https://github.com/alryaz/hass-lkcomu-interrao/files/6680073/home-assistant.log)

**Comment by alryaz** [comment]
Исправлено<sup>1</sup> в v0.0.16, реаутентификация стояла не на всех вызовах (только на обновлениях объектов)

<sup>1</sup> Всё таки это не совсем исправление, а некий обход ошибки; требуется более детальный разбор ошибок, кой запланирован на `>=0.1.0`
