### ISSUE TITLE
Недоступна информация о льготах из ЛК Мосэнерго

### ISSUE THREAD

**Issue by cfdresearch** [alryaz/hass-lkcomu-interrao#7]
Добрый день.

 Не подгружается информация о льготах из ЛК Мосэнерго в HA:
![mosenergo](https://user-images.githubusercontent.com/22324644/123395083-7a6b3380-d5a8-11eb-8b5a-f0658dafb5a0.png)

При этом в HA:
![HA](https://user-images.githubusercontent.com/22324644/123395296-b7372a80-d5a8-11eb-8d20-b7295581bc5f.png)

Все остальные поля прогружаются без проблем.

**Comment by alryaz** [comment]
Здравствуйте! Не сталкивался с таким полем (с сервера они приходят в текстовом формате). Могу я Вас попросить связаться со мной через Telegram? (@alryaz)

**Comment by alryaz** [comment]
v0.0.18 добавляет информацию о льготах
