### ISSUE TITLE
Блокируется доступ.

### ISSUE THREAD

**Issue by MaximSN** [alryaz/hass-lkcomu-interrao#9]
Сначала отвалились счётчики. После перезагрузки в логах такое сообщение:
Ip у меня серый, сижу за nat.
Я конечно позвоню в ТП, но может уже есть прецеденты?

Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.lkcomu_interrao
Source: custom_components/lkcomu_interrao/__init__.py:277
Integration: Личный кабинет Интер РАО (Энергосбыт) (documentation, issues)
First occurred: 8:16:35 (7 occurrences)
Last logged: 8:20:37

[moscow/m***o@g***m] Невозможно выполнить авторизацию: EnergosbytException('Authentication failed', 122, 'Уважаемый пользователь<br>с Вашего IP-адреса <b>(109.252.184.93)</b> была зафиксирована вредоносная активность при обращении к Единому Личному кабинету АО Мосэнергосбыт и ООО МосОблЕИРЦ<br>В связи с этим доступ с Вашего IP-адреса был временно заблокирован<br>Для разблокировки доступа или если ваш адрес был заблокирован по ошибке<br>Просим Вас обратиться в службу поддержки пользователей по телефону <b>+7 (499) 550-9-550</b><br>Для обращения в службу поддержки просим Вас запомнить или записать Ваши IP-адрес <b>(109.252.184.93)</b> и (или) этот идентификатор ID: <b>(2021-07-29-05-16-56-2936E7734C248C00)</b> <br>Мы заботимся о безопасности Ваших данных и благодарим за понимание!')

**Comment by alryaz** [comment]
Duplicate of #8
